import '../models/muscle.dart';

/// Maps SVG element IDs to Muscle enum values
const Map<String, Muscle> svgIdToMuscle = {
  // Front view
  'traps_left': Muscle.trapsLeft,
  'traps_right': Muscle.trapsRight,
  'delts_left': Muscle.deltsLeft,
  'delts_right': Muscle.deltsRight,
  'chest_left': Muscle.chestLeft,
  'chest_right': Muscle.chestRight,
  'abs': Muscle.abs,
  'lats_front_left': Muscle.latsFrontLeft,
  'lats_front_right': Muscle.latsFrontRight,
  'triceps_left': Muscle.tricepsLeft,
  'triceps_right': Muscle.tricepsRight,
  'biceps_left': Muscle.bicepsLeft,
  'biceps_right': Muscle.bicepsRight,
  'biceps_brachialis_left': Muscle.bicepsBrachialisLeft,
  'biceps_brachialis_right': Muscle.bicepsBrachialisRight,
  'forearms_left': Muscle.forearmsLeft,
  'forearms_right': Muscle.forearmsRight,
  'quads_left': Muscle.quadsLeft,
  'quads_right': Muscle.quadsRight,
  'calves_left': Muscle.calvesLeft,
  'calves_right': Muscle.calvesRight,
  // Back view
  'lats_back_left': Muscle.latsBackLeft,
  'lats_back_right': Muscle.latsBackRight,
  'lowerlats_back_left': Muscle.lowerLatsBackLeft,
  'lowerlats_back_right': Muscle.lowerLatsBackRight,
  'glutes_left': Muscle.glutesLeft,
  'glutes_right': Muscle.glutesRight,
  'hamstrings_left': Muscle.hamstringsLeft,
  'hamstrings_right': Muscle.hamstringsRight,
};

/// Reverse mapping from Muscle to SVG ID
const Map<Muscle, String> muscleToSvgId = {
  Muscle.trapsLeft: 'traps_left',
  Muscle.trapsRight: 'traps_right',
  Muscle.deltsLeft: 'delts_left',
  Muscle.deltsRight: 'delts_right',
  Muscle.chestLeft: 'chest_left',
  Muscle.chestRight: 'chest_right',
  Muscle.abs: 'abs',
  Muscle.latsFrontLeft: 'lats_front_left',
  Muscle.latsFrontRight: 'lats_front_right',
  Muscle.tricepsLeft: 'triceps_left',
  Muscle.tricepsRight: 'triceps_right',
  Muscle.bicepsLeft: 'biceps_left',
  Muscle.bicepsRight: 'biceps_right',
  Muscle.bicepsBrachialisLeft: 'biceps_brachialis_left',
  Muscle.bicepsBrachialisRight: 'biceps_brachialis_right',
  Muscle.forearmsLeft: 'forearms_left',
  Muscle.forearmsRight: 'forearms_right',
  Muscle.quadsLeft: 'quads_left',
  Muscle.quadsRight: 'quads_right',
  Muscle.calvesLeft: 'calves_left',
  Muscle.calvesRight: 'calves_right',
  Muscle.latsBackLeft: 'lats_back_left',
  Muscle.latsBackRight: 'lats_back_right',
  Muscle.lowerLatsBackLeft: 'lowerlats_back_left',
  Muscle.lowerLatsBackRight: 'lowerlats_back_right',
  Muscle.glutesLeft: 'glutes_left',
  Muscle.glutesRight: 'glutes_right',
  Muscle.hamstringsLeft: 'hamstrings_left',
  Muscle.hamstringsRight: 'hamstrings_right',
};
